<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>PrestigeManager</RootNamespace>
    <AssemblyName>PrestigeManager</AssemblyName>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="spt-common">
      <HintPath>..\..\..\BepInEx\plugins\spt\spt-common.dll</HintPath>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>..\..\..\BepInEx\plugins\spt\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\..\..\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
	<None Include="config\prestige_config.json">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
  </ItemGroup>

  <Target Name="CopyConfig" AfterTargets="PostBuildEvent">
	<Copy
	  SourceFiles="$(ProjectDir)config\prestige_config.json"
	  DestinationFolder="$(ProjectDir)..\..\BepInEx\plugins\PrestigeManager\"
	  Condition="!Exists('$(ProjectDir)..\..\BepInEx\plugins\PrestigeManager\config\prestige_config.json')" />
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;$(TargetPath)&quot; &quot;$(ProjectDir)\..\..\..\BepInEx\plugins\$(TargetFileName)&quot;" />
  </Target>

</Project>
